version: '3.4'
services: 
  app:
    build: 
      context: ./testapps/cnn-cerebro-api
      dockerfile: dockerfile
    networks:
      - default
    environment:
      ENVIRONMENT: dev
      LOGZIO_TOKEN: YBJpcTjcrpLOBpsmGxunSyBdQMIBAfwC
  cache:
    build:
      context: ./varnish
      dockerfile: dockerfile
      args: 
        vclfile: ./vcls/default.vcl
    networks: 
      - default
    links:
      - app
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes: 
      - ./varnish/vcls:/tmp/Varnish-Cache-varnish-2.1.5/vcls
networks:
  default: