version: '3.4'
services: 
  app:
    build: 
      context: ./app # You can change this to any app you copy into this project and run the cache against it specifically.
      dockerfile: dockerfile
    networks:
      - default
  cache:
    build:
      context: ./varnish
      dockerfile: dockerfile
      args: 
        VCLFILE: ./vcls/long_lived_cache.vcl
    networks: 
      - default
    links:
      - app
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes: 
      - ./varnish/vcls:/tmp/Varnish-Cache-varnish-2.1.5/vcls
networks:
  default: