version: '3.4'
services: 
  app:
    build: 
      context: ./app
      dockerfile: dockerfile
    networks:
      - default
    environment:
      PORT: 4503
  cache:
    build:
      context: ./varnish
      dockerfile: dockerfile
    networks: 
      - default
    links:
      - app
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
networks:
  default: