FROM ubuntu:12.04.5

ARG VCLFILE=./vcls/default.vcl

RUN apt-get update

RUN apt-get install -y build-essential automake libtool pkg-config libpcre3 libpcre3-dev python-docutils nano wget

WORKDIR /tmp

RUN wget --no-check-certificate https://github.com/varnish/Varnish-Cache/archive/varnish-2.1.5.tar.gz && tar -xvf varnish-2.1.5.tar.gz

WORKDIR /tmp/Varnish-Cache-varnish-2.1.5

RUN ./autogen.sh
RUN ./configure
RUN make && make install
RUN ldconfig

COPY ./check_vcl.sh .
# COPY ./vcls ./vcls

RUN chmod +x ./check_vcl.sh

# ENV VCL_CONFIG /tmp/Varnish-Cache-varnish-2.1.5/vcls/default.vcl
ENV DEFAULT_VCL_FILE ${VCLFILE}
ENV CACHE_SIZE 64m
ENV VARNISHD_PARAMS -p default_ttl=3600 -p default_grace=3600 -a 0.0.0.0:80

RUN echo "varnishd -F -f $vclfile -s malloc,$CACHE_SIZE $VARNISHD_PARAMS"

CMD varnishd -F -f $DEFAULT_VCL_FILE -s malloc,$CACHE_SIZE $VARNISHD_PARAMS